name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:      
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1
      
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        run: make test-coverage
      
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build
